version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
